### ISSUE TITLE
关于文件标签导航

### ISSUE THREAD

**Issue by BlackSinny** [Mengess/document#10]
1. 主页右侧有点空，略微有点影响美观
2. 上面一排大部分都是外战的导航，缺少内部的分类导航
3. 部分用户只想看到技术栈吻合的系列文章

![image](https://user-images.githubusercontent.com/38745744/194812161-5536d666-3916-4ad3-a756-64a439e5b0ca.png)

**Comment by BlackSinny** [comment]
一点优化的小看法，我也准备用这个主题搭一个博客了，感谢博主分享

**Comment by friend-nicen** [comment]
更新了一个大版本，一直没发出来。差不多把你说的这些补齐了，只是有些细节一直没空优化，但也差不多，回去我整理一下，你可以试试😂

**Comment by BlackSinny** [comment]
好的，期待优化升级

**Comment by friend-nicen** [comment]
2.0版本已经上传了，您可以试试，这个issue我就关闭了哈；
