### ISSUE TITLE
关于右上方导航栏配置

### ISSUE THREAD

**Issue by BlackSinny** [Mengess/document#11]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/38745744/194817100-7e7dd3ee-1f11-4774-821d-f774ff5a0462.png">

求问这个导航栏是哪wp后台哪个地方进行配置到呢

**Comment by friend-nicen** [comment]
只有文章分类，快速阅读可以在  后台 - 外观 -菜单进行配置，其他的是写死的。
下一个版本已经改成全部自定义了。😆

**Comment by friend-nicen** [comment]
2.0版本已经上传，顶部导航已经可以完全自定义了，您可以试试，这个issue我就关闭了哈；
