### ISSUE TITLE
请问该主题如何打开评论区接收留言？

### ISSUE THREAD

**Issue by jtzx082** [Mengess/document#14]
请问该主题如何打开评论区接收留言？

**Comment by friend-nicen** [comment]
您好，首先编辑页面 -  右上角的显示选项 - 勾选讨论 - 滚动到下方 - 把允许评论勾选  - 保存即可😁

**Comment by jtzx082** [comment]
非常抱歉，我还是没有找到操作的地方，是在主题设置这里操作吗？还请您再给我说说。非常感谢！
