### ISSUE TITLE
反馈个bug 产生原因不明

### ISSUE THREAD

**Issue by FunnyRyan** [Mengess/document#23]
如下图所示：
![QQ截图20221020125840](https://user-images.githubusercontent.com/37170909/196860288-86186a15-ba04-4c73-9d78-267cc3f03368.png)

**Comment by friend-nicen** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️，我去翻翻代码，稍等

**Comment by friend-nicen** [comment]
看着像是json没有被前端转成对象，请问方便把你wp后台给我吗🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by friend-nicen** [comment]
微信号 good7341，期待您的联系！
