### ISSUE TITLE
右侧小工具 增加几个呗？

### ISSUE THREAD

**Issue by imrelax** [Mengess/document#25]
希望增加 标签云
然后自定义功能。
目前我要自定义一些广告进去会有样式有点小问题 会多个小点点。
![QQ图片20221115134859](https://user-images.githubusercontent.com/33931868/201867387-f1551177-5f72-4161-b1bd-acb7d8c15d7f.png)

然后文章内 也是否可以考虑增加下 广告位呢？

**Comment by friend-nicen** [comment]
🐱‍🐉🐱‍🐉🐱‍🐉没找到好看的、合适的样式，有推荐嘛

**Comment by imrelax** [comment]
没有什么好的推荐哦。。 但是 文字和图片 或者 html 代码 可以稍微 控制下。 
至少右侧小工具我自定义图片 代码 这些 把那个 黑点 多出来的 <li> 的这个代码去掉！这个可以处理下！

然后 文章上下增加个广告位。方便放一些代码！控制下页面 不错位  不出这些多余的就可以了！

**Comment by friend-nicen** [comment]
我懂了，搞一个可以自定义html、css样式的、风格统一的小工具🤦‍♂️

**Comment by friend-nicen** [comment]
我懂了，搞一个可以自定义html、css样式的小工具🤦‍♂️

**Comment by imrelax** [comment]
是的。 至少保证风格统一就可以了。 比如 标签云确实 会麻烦点的。
但是就基于目前风格样式 完全可以做出来个 用来放个广告代码啥的完全没问题！

**Comment by friend-nicen** [comment]
Ok，我记录一下，提上日程。🐱‍🐉
