### ISSUE TITLE
做一个文章置顶功能呗

### ISSUE THREAD

**Issue by imrelax** [Mengess/document#26]
后台 主题设置里面增加个文章置顶功能。 设置文章ID  置顶到首页显示。
然后给置顶文章增加个效果。加个图片 icon什么的 或者颜色自定义 一下！

**Comment by friend-nicen** [comment]
wordpress自带的置顶的功能，编辑的时候把置顶勾上就行🤣🤣🤣

**Comment by imrelax** [comment]
哦。。  我没看出来。 因为 置顶文章 没特别效果。 所以我没看出来。 我以为是我正常的文章！哎。。

**Comment by friend-nicen** [comment]
🤣🤣🤣，加个代表置顶的小图标

**Comment by imrelax** [comment]
是的。会有特殊意义。 会更明显点！
