### ISSUE TITLE
作者相关信息这里微调下

### ISSUE THREAD

**Issue by imrelax** [Mengess/document#27]
![](https://user-images.githubusercontent.com/33931868/201875281-d7c0ed9e-31ca-4dd2-9fdf-dea381b9cc0a.png)

职业和昵称靠的太近。 我试过了增加空格或者空格符 &nbsp; 没用，
当前我这里显示 两个靠的太近有点不好看，稍微增加点 字符吧。 
你的昵称因为 友人a丶   、后面是自带了个空白字符 所以看不出来。我 昵称因为没有其他字符 所以2个就靠的太近了。不好看。这个稍微微调下吧。

**Comment by imrelax** [comment]
![](https://user-images.githubusercontent.com/33931868/201876072-cec650e6-8cb7-407f-9611-7e6d776386f8.png)

有个空格 稍微隔开下 好看点！

**Comment by friend-nicen** [comment]
🤣🤣🤣确实近了点，等下次更新。

现在的话，你可以试着加 &nbsp; 转义符来展示空格

**Comment by friend-nicen** [comment]
&   nbsp;     把它们连起来
