### ISSUE TITLE
博客logo修改后。点击保存会恢复默认

### ISSUE THREAD

**Issue by snakexgc** [Mengess/document#3]
修改位置或者直接换用图床链接都不行，点击保存后就会恢复默认位置

wd 6.0.1 
php 7.4.21

**Comment by friend-nicen** [comment]
已收到反馈，我去排查一下。

**Comment by snakexgc** [comment]
我开始怀疑是不是我环境有问题了，我写好的文章在wd后台能看到，可以编辑，点击网站上面的文章就会404，我等会儿换个主题试试

**Comment by friend-nicen** [comment]
自信点，大兄弟，logo修改确实有问题，404的话，伪静态配置了吗？

**Comment by snakexgc** [comment]
没设置伪静态之前是nginx自己预设的404界面，伪静态开启后是您代码里面的404界面
![12876A25](https://user-images.githubusercontent.com/78722169/180652517-3275866e-5ced-4f0c-a0f1-6329903d96e1.png)

**Comment by snakexgc** [comment]
404应该是配置问题，换一个也一样，大佬先修一修logo的bug吧，给大佬添麻烦了

**Comment by friend-nicen** [comment]
好咧。早点休息

**Comment by friend-nicen** [comment]
问题已经解决，通过重新安装空白的wordpress使用本主题进行测试，按照如下步骤安装后，未发现问题。 显示的页面与 [nicen.cn](https://nicen.cn) 别无二致。

**Comment by friend-nicen** [comment]
2022-07-24版[README.md](https://github.com/friend-nicen/theme-document/blob/c40070a1cab0342e00932272dc8857997be13840/README.md)

**Comment by snakexgc** [comment]
好，我等会儿再去试试（好耶！）

**Comment by friend-nicen** [comment]
今天测试的时候也遇到了昨天你说的404的问题，目前排查出的原因是用了wp-optimized插件，插件缓存了页面。换了主题之后缓存的规则还在，但是匹配不到页面文件了，清除插件缓存之后就恢复了。
