### ISSUE TITLE
无法兼容markwon标题

### ISSUE THREAD

**Issue by xmusphlkg** [Mengess/document#32]
您好，我是用typora编辑markdown文件无法直接复制粘贴文件，图片也无法显示。

并且导出为无格式的html再复制粘贴后，会出现文章左侧目录不识别标题情况。

**Comment by friend-nicen** [comment]
![图片](https://nicen.cn/wp-content/uploads/2023/02/1677219532816.png)，文章左侧那个目录是通过读取wordpress编辑器上面的这个标题元标签生成的。🐱‍🐉跟文章内的html标签（h1、h2）无关

**Comment by friend-nicen** [comment]
没有直接读取html生成是因为涉及到了其它的一些功能（太久远了，记不清了🤣🤣），所以目前需要生成目录的话，需要您手动去添加元标签。
