### ISSUE TITLE
我该如何在新版本中调出这个页面

### ISSUE THREAD

**Issue by oyemao** [Mengess/document#34]
[![pPq4uCV.jpg](https://z1.ax1x.com/2023/09/30/pPq4uCV.jpg)](https://imgse.com/i/pPq4uCV)
如上图，新版的主题后台已经没有这些设置了，但不升级新版又有很多BUG，哭

**Comment by friend-nicen** [comment]
新版本是完全兼容之前版本的功能和内容的，切换到新版后将新增的一些部件和工具选择关闭，页面方面能做到和旧版一致。

**Comment by friend-nicen** [comment]
新版本是完全兼容之前版本的功能和内容的，切换到新版后将新增的一些部件和工具选择关闭，页面方面能做到和旧版一致。
