### ISSUE TITLE
后台管理文章分类异常

### ISSUE THREAD

**Issue by haobo-zhu** [Mengess/document#35]
在后台管理新增文章分类提交成功时，无法完成页面自动跳转刷新，提交按钮一直在转圈圈

**Comment by friend-nicen** [comment]
![image](https://github.com/friend-nicen/theme-document/assets/84662035/eab1210d-916a-462c-b62a-07d849334142)
我这边正常哦，你换个主题再试下问题还在不在。问题是有，但是我也不确定是不是主题的原因。🤔

**Comment by aspinacher** [comment]
更换其他主题后可恢复正常 ，在提交后，右侧的新增分类没有刷新，停留在截图的界面
![image](https://github.com/friend-nicen/theme-document/assets/33769645/c6bd7c9a-fa70-41bf-94a6-5444e32e7aa4)

**Comment by friend-nicen** [comment]
加wx good7341，我来调试调试😁

**Comment by friend-nicen** [comment]
最新版本已修复
