### ISSUE TITLE
文章显示bug

### ISSUE THREAD

**Issue by ligeaaa** [Mengess/document#37]

**Comment by ligeaaa** [comment]
<img width="922" alt="image" src="https://github.com/friend-nicen/theme-document/assets/101978760/e7578a82-2309-45bb-855e-b5ff585d297e">
理论上应该可以正确显示html格式文本，然而实际上并不能
![image](https://github.com/friend-nicen/theme-document/assets/101978760/5e656750-a805-4733-aa48-14650f84ecd8)
（在其他zhu主题中可以正常显示

**Comment by friend-nicen** [comment]
您这个是默认的经典编辑器吗

**Comment by ligeaaa** [comment]
> 您这个是默认的经典编辑器吗
应该是的，虽然装了WP Githuber MD插件后，编辑器有点变化？

**Comment by friend-nicen** [comment]
![image](https://github.com/friend-nicen/theme-document/assets/84662035/74d94f19-bb3c-40dd-9440-3f56b9d3ec88)
![image](https://github.com/friend-nicen/theme-document/assets/84662035/ec9d8fee-9308-46de-a64f-4cd4d0bcf183)
我测试了一下，经典编辑器输入html，展示挺正常的

**Comment by ligeaaa** [comment]
> ![image](https://user-images.githubusercontent.com/84662035/283300714-74d94f19-bb3c-40dd-9440-3f56b9d3ec88.png) ![image](https://user-images.githubusercontent.com/84662035/283300746-ec9d8fee-9308-46de-a64f-4cd4d0bcf183.png) 我测试了一下，经典编辑器输入html，展示挺正常的

好的，那我再自己看看
