### ISSUE TITLE
document结合markdown插件实现目录显示

### ISSUE THREAD

**Issue by makaixindalao** [Mengess/document#40]
大佬，我在结合markdown插件实现目录显示的时候遇到了问题
目前我通过修改为HTML去识别到了markdown转化出来的目录，但是点击模块并不会跳转到对应位置

目录形式
### 2

**Comment by friend-nicen** [comment]
文章目录现在有两个解析模式：【插件元标签】和 【html标签】，后者有BUG，也就是点了不会正常跳转，还没来得及修，到时候修了我再推送一下。

**Comment by friend-nicen** [comment]
已修复
