### ISSUE TITLE
php代码报错

### ISSUE THREAD

**Issue by LuG3Zz** [Mengess/document#41]
作者你好，添加小工具的文章推荐时，出现这个效果：
![image](https://github.com/friend-nicen/theme-document/assets/52660939/fdee6022-4f8c-4f97-ba96-260311a096d7)
请问该如何解决？是php版本的原因吗？
![image](https://github.com/friend-nicen/theme-document/assets/52660939/9a24c760-e016-4609-8e78-43a8fe12b80f)

**Comment by friend-nicen** [comment]
换成php7.4试试。

**Comment by friend-nicen** [comment]
这个文件里用到了匿名函数，这个语法好像得php7.3+才支持
