### ISSUE TITLE
点赞可以一直点，是不是加个IP绑定或者什么唯一值去限制一下

### ISSUE THREAD

**Issue by amiaoapp** [Mengess/document#43]
这个点赞一直可以点，那就没有意义了
<img width="192" alt="29228" src="https://github.com/friend-nicen/theme-document/assets/13944985/f6c2a35e-019d-4014-a9d2-ce47a3dc5b60">

**Comment by amiaoapp** [comment]
刷新下 ，点赞又没了

**Comment by friend-nicen** [comment]
我这点赞就图一乐子，🤦‍♂️。你要是在我的站测试，刷新没了那是正常的，因为页面都有静态缓存

**Comment by amiaoapp** [comment]
> 我这点赞就图一乐子，🤦‍♂️。你要是在我的站测试，刷新没了那是正常的，因为页面都有静态缓存

那要不要完善下，绑定个键值，比如IP，当天只能点赞一次

**Comment by friend-nicen** [comment]
下次更新的时候我改改：在本地加个缓存验证，点过了不让点。这样方便也省资源，基本满足需求

**Comment by amiaoapp** [comment]
可以的
