### ISSUE TITLE
fail to use WP Githuber MathJax module when using document theme

### ISSUE THREAD

**Issue by HaibinLai** [Mengess/document#45]
![QQ20240920-225717](https://github.com/user-attachments/assets/c5476d77-c2dd-4f0e-a363-877e99a1fa91)
![QQ20240920-225912](https://github.com/user-attachments/assets/e2d79f21-961f-4489-98c0-366d093fb6fe)

如图，我在主题中使用了WP Githuber插件，并尝试里边的mathjax功能，但是结果无法显示。

WP Githuber version: 	1.16.3
theme version: 当前版本 1.2.9

mathjax module:

![QQ20240920-230213](https://github.com/user-attachments/assets/64851456-a2f9-41dc-a3d4-3fd6e6f61378)

**Comment by HaibinLai** [comment]
![QQ20240920-230415](https://github.com/user-attachments/assets/5be7be0b-8f4c-45ac-bb75-8484dbeca7e3)

**Comment by friend-nicen** [comment]
![image](https://github.com/user-attachments/assets/0ddb189e-9c29-4e22-86dd-6163ac1761a8)
![image](https://github.com/user-attachments/assets/7f87860d-6e4a-48e5-84fd-9c59a4b4c44a)

这样试试：

[mathjax]公式[/mathjax]

**Comment by HaibinLai** [comment]
谢谢你！解决了
