### ISSUE TITLE
文章左侧目录空白AND每次在后台点击发布文章不会自动跳转，要手动返回前一个页面

### ISSUE THREAD

**Issue by jasminesor** [Mengess/document#6]
求教如何设置文章左侧的目录部分显示文章大纲呀？我的文章应该是有h1,h2标题的，但是发布后左侧目录没有信息。

**Comment by friend-nicen** [comment]
编写文章的时候，文章编辑器上面有一排小图标，有三个 H1、H2、H3的图标。

**Comment by friend-nicen** [comment]
假设我选中编辑器内的标题文字  “API介绍” ，然后点击H1的图标。最后的格式就是：[h1]API介绍[/h1]，只有这样的写出来的标题才会出现在左侧的文章目录。0.0
![1658902404529](https://user-images.githubusercontent.com/84662035/181181180-c01b1359-907e-432c-a3c4-db87948744b5.jpg)

**Comment by friend-nicen** [comment]
关于【每次在后台点击发布文章不会自动跳转，要手动返回前一个页面】，请问 “自动跳转” 这个您具体指的是什么场景呢？

**Comment by jasminesor** [comment]
谢谢您的答复!!!
我描述的是这样的场景, 在后台文章发布页面, 编辑完一篇文章后, 点击发布(或者更新), 如下
***@***.***
点击发布或者更新以后, 会一直停留在下面这个空白页面.
***@***.***
貌似就是每次发布文章没有自动跳转?

最后, 感谢哇, 按照您的方法成功显示目录了!
分析原因可能是：我的文章都是在markdown写好的，然后直接复制到文章编辑页面。查看编辑页面的文本发现, 二级标题“API”的代码形式是<h2>API</h2>, 也许是复制的时候自动把标签转换了吧…. 而您的主题识别目录用的可能是[h2]API[/h2], 所以只要先把标题”API”选中,格式改为段落后再点击H2图标就好了哈哈哈哈.可能我理解的不对,但是好在解决啦. 感谢!!

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年7月27日 14:20
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [friend-nicen/theme-document] 文章左侧目录空白AND每次在后台点击发布文章不会自动跳转，要手动返回前一个页面 (Issue #6)


关于【每次在后台点击发布文章不会自动跳转，要手动返回前一个页面】，请问 “自动跳转” 这个您具体指的是什么场景呢？

―

**Comment by friend-nicen** [comment]
我这个wordpress每次发布或者更新文章，仍然会停留在文章编辑页面。然后会有如下的显示，点击查看后跳转到当前文章页面。（难道我们的wp不一样吗=.=）


![1658904604998](https://user-images.githubusercontent.com/84662035/181181056-98c6ed94-92a8-4de7-8b1d-b05a4bc8c8cd.jpg)

**Comment by jasminesor** [comment]
这样呀, 那应该是我的环境问题. 可能是插件和主题冲突了吧T_T. 我去排查下哈哈哈. 谢谢哦!~

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年7月27日 14:52
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [friend-nicen/theme-document] 文章左侧目录空白AND每次在后台点击发布文章不会自动跳转，要手动返回前一个页面 (Issue #6)


我这个wordpress每次发布或者更新文章，仍然会停留在文章编辑页面。然后会有如下的显示，点击查看后跳转到当前文章页面。（难道我们的wp不一样吗=.=）
[1658902404529]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F84662035%2F181180675-4fe0d625-9465-476f-b35e-234206ec1a34.jpg&data=05%7C01%7C%7C751aa51052614f0c077608da6f9c8f64%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637945015478814761%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lF6uGpWuMqtr%2Bg%2B2gho%2BOKt4y89%2FgNeE3k34yeUg6X4%3D&reserved=0>

―

**Comment by friend-nicen** [comment]
![3B6D337B5A0DD17B184959D63A02CECD](https://user-images.githubusercontent.com/84662035/181182632-51a70e72-70d5-4344-99a8-1f442e4aa29f.gif)
