### ISSUE TITLE
markdown 文章支持

### ISSUE THREAD

**Issue by BlackSinny** [Mengess/document#9]
文章目录是否考虑支持下marddown语法呢
实测发现WP Editor.md 展示无法支持
很多人都习惯在本地typora 写好，然后直接复制到wp后台，不支持markdows的话写起来有点麻烦了。
其他的都很好，给个小星星

**Comment by friend-nicen** [comment]
你这个是通过哪个插件实现的？
因为wp的编辑器本身是不支持mearkdown语法的，所以wp兼容markdown语法有很多种实现方式；
针对markdown实现文章目录的话，适配起来每种方式的处理可能都不一样。

恰到好处的方式的话，只能针对主流的方式去适配。

**Comment by BlackSinny** [comment]
WP Editor.md

**Comment by jtzx082** [comment]
请问一下，如何打开评论区，接收留言？
